# CircleCI configuration for gallery-app
version: 2.1
orbs:
  node: circleci/node@5
jobs:
  test-node:
    executor: node/default
    resource_class: medium
    parallelism: 2
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
      NODE_ENV: test
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          cache-version: v1
      - run:
          name: Install test reporter
          command: yarn add jest-junit --ignore-workspace-root-check
      - run:
          name: Run tests with parallelism
          command: |
            TEST_FILES=$(circleci tests glob "tests/**/*.test.js" | circleci tests split --split-by=timings)
            yarn run test --ci --reporters=default --reporters=jest-junit $TEST_FILES
      - store_test_results:
          path: ./test-results/
      - store_artifacts:
          path: ./test-results/
          destination: test-results
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'
workflows:
  build-and-test:
    jobs:
      - test-node
